package FocusEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.*;

/**
 *
 * @author Lalo
 */
public class EjemploFoco extends javax.swing.JFrame implements FocusListener {

    JPanel panel = new JPanel();
    FlowLayout flujo = new FlowLayout();
    JLabel nombre = new JLabel("Nombre:", JLabel.LEFT);
    JTextField campo = new JTextField(20);
    JLabel mensaje = new JLabel(" ");
    
    JPanel panel2 = new JPanel();
    JLabel apellido = new JLabel("Apellido:", JLabel.LEFT);
    JTextField campo2 = new JTextField(20);
    JLabel mensaje2 = new JLabel(" ");
    
    JPanel panel3 = new JPanel();
    JLabel edad = new JLabel("Edad:", JLabel.LEFT);
    JTextField campo3 = new JTextField(20);
    JLabel mensaje3 = new JLabel(" ");
    
    JPanel panel4 = new JPanel();
    JLabel direccion = new JLabel("Direccion:", JLabel.LEFT);
    JTextField campo4 = new JTextField(20);
    JLabel mensaje4 = new JLabel(" ");
    
    JPanel panel5 = new JPanel();
    JLabel Telefono = new JLabel("Telefono:", JLabel.LEFT);
    JTextField campo5 = new JTextField(20);
    JLabel mensaje5 = new JLabel(" ");
    
    public EjemploFoco() {
        
        super("EJemplo de FocusListener");
        setSize(470,150);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        panel.setLayout(flujo);
        panel.setBorder(BorderFactory.createEmptyBorder(20, 20, 0, 20));
        panel.add(nombre);
        campo.addFocusListener(this);
        panel.add(campo);
        panel.add(mensaje);
       
        panel2.setLayout(flujo);
        panel2.setBorder(BorderFactory.createEmptyBorder(0, 20, 20, 20));
        panel2.add(apellido);
        campo2.addFocusListener(this);
        panel2.add(campo2);
        panel2.add(mensaje2);
        
        panel3.setLayout(flujo);
        panel3.setBorder(BorderFactory.createEmptyBorder(10, 0, 20, 20));
        panel3.add(edad);
        campo3.addFocusListener(this);
        panel3.add(campo3);
        panel3.add(mensaje3);
        
        panel4.setLayout(flujo);
        panel4.setBorder(BorderFactory.createEmptyBorder(0, 20, 20, 20));
        panel4.add(direccion);
        campo4.addFocusListener(this);
        panel4.add(campo4);
        panel4.add(mensaje4);
        
        panel5.setLayout(flujo);
        panel5.setBorder(BorderFactory.createEmptyBorder(0, 20, 20, 20));
        panel5.add(Telefono);
        campo5.addFocusListener(this);
        panel5.add(campo5);
        panel5.add(mensaje5);
       
        GridLayout grilla = new GridLayout(5,4);
        setLayout(grilla);
        add(panel);add(panel2);add(panel4);add(panel5);add(panel3);
        //pack();
        setVisible(true);
        
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjemploFoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjemploFoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjemploFoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjemploFoco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjemploFoco().setVisible(true);
            }
        });
    }

    @Override
    public void focusGained(FocusEvent e) {
        if(e.getSource() == campo){
            mensaje.setText("<--Escribe tu nombre.");
        }
        if(e.getSource() == campo2){
            mensaje2.setText("<--Escribe tu Apellido.");
        }
        if(e.getSource() == campo3){
            mensaje3.setText("<--Escribe tu Edad.");
        }
        if(e.getSource() == campo4){
            mensaje4.setText("<--Escribe tu Direccion.");
        }
        if(e.getSource() == campo5){
            mensaje5.setText("<--Escribe tu Telefono.");
        }
        

        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void focusLost(FocusEvent e) {
        if(e.getSource() == campo){
            mensaje.setText("             ");
        }
        if(e.getSource() == campo2){
            mensaje2.setText("            ");
        }
        if(e.getSource() == campo3){
            mensaje3.setText("            ");
        }
        if(e.getSource() == campo4){
            mensaje4.setText("            ");
        }
        if(e.getSource() == campo5){
            mensaje5.setText("            ");
        }
        
        
        

        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
